package labrom.litlbro.state;

public enum Event {
    IMPLICIT_NEXT,
    BACK,
    TAP_SHORTCUT,
    EDIT_SHORTCUTS,
    TAP_SITE_SUGGESTION,
    TAP_SEARCH_SUGGESTION,
    SEARCH_BOX_TEXT,
    SEARCH_BOX_EMPTY,
    SEARCH_BOX_DONE,
    TAP_JS_TOGGLE,
    TAP_HW_MENU,
    PAGE_FINISHED_LOADING,
    TAP_LINK

}
